version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node/Backend-repo
permissions:
 - object: /home/ec2-user
	 owner: ec2-user
	 group: ec2-user
	 type:
	   - directory
		 - file		
hooks:
 BeforeInstall:
   - location: scripts/BeforeInstall.sh
     timeout: 180
     runas: root
Install:
   - location: scripts/Install.sh
      timeout: 300
      runas: ec2-user			
AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: ec2-user
  # ApplicationStart:
  #   - location: scripts/application_start.sh
  #     timeout: 300
  #     runas: ec2-user
# ValidateService: