version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node/Backend-repo
hooks:
 BeforeInstall:
   - location: scripts/BeforeInstall.sh
     timeout: 180
     runas: root
Install:
   - location: scripts/Install.sh
      timeout: 300
      runas: ec2-user			
AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: ec2-user