version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node/Backend-repo
hooks:
ApplicationStop:
DownloadBundle:
 BeforeInstall:
   - location: scripts/BeforeInstall.sh
     timeout: 300
     runas: ec2-user
Install:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
# ValidateService:
      